### ISSUE TITLE
Building without threads gives linking error for: git___load

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#5663]
I run into a bug introduced by https://github.com/libgit2/libgit2/pull/5594 when building `-DTHREADSAFE=OFF`. 

```
[ 47%] Building C object src/CMakeFiles/git2internal.dir/index.c.obj
In file included from C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/common.h:81,
                 from C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/index.h:10,
                 from C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/index.c:8:
C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/index.c: In function 'git_index_set_caps':
C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/thread-utils.h:344:32: warning: implicit declaration of function 'git___load'; did you mean 'git__load'? [-Wimplicit-function-declaration]
 #define git__load(ptr) (void *)git___load((void * volatile *)&ptr)
                                ^~~~~~~~~~
C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/thread-utils.h:344:32: note: in definition of macro 'git__load'
 #define git__load(ptr) (void *)git___load((void * volatile *)&ptr)
                                ^~~~~~~~~~
C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/index.c:50:46: note: in expansion of macro 'GIT_REFCOUNT_OWNER'
 #define INDEX_OWNER(idx) ((git_repository *)(GIT_REFCOUNT_OWNER(idx)))
                                              ^~~~~~~~~~~~~~~~~~
C:/msys64/home/mingw-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/index.c:574:26: note: in expansion of macro 'INDEX_OWNER'
   git_repository *repo = INDEX_OWNER(index);
                          ^~~~~~~~~~~
```

Eventually the build succeeds, however the `libgit2.a` library gives linking errors looking for `git___load`. I think the problem is that `git___load` is defined within a `#ifdef GIT_THREADS` block, but not the macro that uses it.

This is libgit2 1.1.0 on mingw-w64 with gcc 8.3.0. 
cc @lhchavez
