### ISSUE TITLE
Undefined symbols _htonll on OS X 10.9 and earlier

### ISSUE THREAD

**Issue by ryandesign** [libgit2/libgit2#5613]
Hi, I'm a MacPorts developer. We recently updated our libgit2 to 1.0.1 and found that it builds fine on OS X 10.10 and later but [fails on 10.9 and earlier](https://trac.macports.org/ticket/61057) because of your use of `htonll` which was not added to OS X until 10.10.

You have some code in deps/ntlmclient/compat.h (see #5414) for defining compatibility versions of `htonll` on various systems but you haven't considered OS X there.

Instead of having to handle each operating system individually, it might be better to have your cmake script test whether `htonll` is available and use a compatibility implementation otherwise. That would automatically handle OS X 10.9 and earlier and any other systems you haven't yet considered.

### Reproduction steps

build libgit2

### Expected behavior

successful build

### Actual behavior

[build failure](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/125341/steps/install-port/logs/stdio):

```
deps/ntlmclient/ntlm.c:1129:16: warning: implicit declaration of function 'htonll' is invalid in C99 [-Wimplicit-function-declaration]
        local_nonce = htonll(ntlm->nonce);
                      ^
```
```
Undefined symbols for architecture x86_64:
  "_htonll", referenced from:
      _ntlm_client_response in ntlm.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgit2.1.0.1.dylib] Error 1
```

### Version of libgit2 (release number or SHA1)

1.0.1

### Operating system(s) tested

OS X (macOS) 10.9.5

**Comment by pks-t** [comment]
> Instead of having to handle each operating system individually, it might be better to have your cmake script test whether htonll is available and use a compatibility implementation otherwise. That would automatically handle OS X 10.9 and earlier and any other systems you haven't yet considered.

Yeah, you're right about this. I've opened #5614 to fix this once and for all.

**Comment by ethomson** [comment]
Fixed via #5658
