### ISSUE TITLE
recent regression adding http headers to push/fetch

### ISSUE THREAD

**Issue by josharian** [libgit2/libgit2#5385]
### Reproduction steps

I use a bearer token in an Authorization header to authorize with my server.

Using git2go:

```go
opts := new(git.PushOptions)
opts.Headers = []string{"Authorization: Bearer " + bearer}
err := remote.Push(refspecs, opts)
```

This worked until recently. At current master (559751714b23f63ead726e9a773be8b07e3551ae), there is no Authorization header present when the request reaches the server.

I have bisected to one of these three commits:

* 7372573b5f1113b8522e2588fac1c529ddcedb0a
* bf55facf15e5b6897ff7305162a77d92089f6c82
* b9c5b15a7958ab4ecb83504a6d858efd18610297

The first two of these commits don't compile: `src/transports/http.c:89:2: error: unknown type name 'git_http_authtype_t'`. The last one seems pretty plausible.

cc @ethomson

**Comment by josharian** [comment]
Just to make sure, I threaded `GIT_OPT_ENABLE_HTTP_EXPECT_CONTINUE` through to git2go and enabled it; it did not fix the problem.

**Comment by pks-t** [comment]
Thanks for your report! I bet it's commit b9c5b15a7958ab4ecb83504a6d858efd18610297, which refactors basically everything related to HTTP.

**Comment by pks-t** [comment]
Could you please verify that #5387 fixes your issue?

**Comment by josharian** [comment]
#5387 fixes it, thanks!
