### ISSUE TITLE
1.5.0 - OpenSSL include path missing when using alternate prefix path

### ISSUE THREAD

**Issue by chargr** [libgit2/libgit2#6371]
### Reproduction steps
Do not have any locally installed openssl devel packages.
Install a build of OpenSSL outside of usual search paths.

```
mkdir build && cd build
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=${PREFIX} \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_SYSTEM_PREFIX_PATH="/path/to/openssl" \
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1 \
..

make
```

Using pkg-config instead of CMAKE_SYSTEM_PREFIX_PATH has the same result.

### Expected behavior
This worked in 1.4.4 and probably built/linked to openssl in the alternate path.

### Actual behavior
```
Scanning dependencies of target git2_cli
[ 30%] Building C object src/cli/CMakeFiles/git2_cli.dir/cmd.c.o
[ 30%] Building C object src/cli/CMakeFiles/git2_cli.dir/cmd_cat_file.c.o
[ 30%] Building C object src/cli/CMakeFiles/git2_cli.dir/cmd_clone.c.o
In file included from /build/tmp/libgit2/src/util/hash/sha.h:21:0,
                 from /build/tmp/libgit2/src/util/hash.h:13,
                 from /build/tmp/libgit2/src/util/futils.h:17,
                 from /build/tmp/libgit2/src/cli/cmd_clone.c:17:
/build/tmp/libgit2/src/util/hash/openssl.h:14:26: fatal error: openssl/sha.h: No such file or directory
compilation terminated.
make[2]: *** [src/cli/CMakeFiles/git2_cli.dir/cmd_clone.c.o] Error 1
make[1]: *** [src/cli/CMakeFiles/git2_cli.dir/all] Error 2
make: *** [all] Error 2
```

### Version of libgit2 (release number or SHA1)
1.5.0

### Operating system(s) tested
CentOS 6/Linux

**Comment by adamryczkowski** [comment]
I have the same issue. To reproduce: just install the openssl with [Spack](https://github.com/spack/spack) rather than using package manager. I am happy to provide more details.

**Comment by mjsteinbaugh** [comment]
I can reproduce this as well and am seeing the same issue with 1.5.1.

**Comment by frindler** [comment]
I have the same issue still in 1.7.2. Any fixes or ideas?
