### PR TITLE
Fix warning C4133 incompatible types in MSVC

### PR DESCRIPTION
**Pull request by csware**
Introduced in commit b433a22a979ae78c28c8b16f8c3487e2787cb73e.

### CODE REVIEW

**Comment by ethomson** [comment]
Thanks!
