### PR TITLE
transports: http: fix custom headers not being applied

### LINKED ISSUE #5385: recent regression adding http headers to push/fetch
### Reproduction steps

I use a bearer token in an Authorization header to authorize with my server.

Using git2go:

```go
opts := new(git.PushOptions)
opts.Headers = []string{"Authorization: Bearer " + bearer}
err := remote.Push(refspecs, opts)
```

This worked until recently. At current master (559751714b23f63ead726e9a773be8b07e3551ae), there is no Authorization header present when the request reaches the server.

I have bisected to one of these three commits:

* 7372573b5f1113b8522e2588fac1c529ddcedb0a
* bf55facf15e5b6897ff7305162a77d92089f6c82
* b9c5b15a7958ab4ecb83504a6d858efd18610297

The first two of these commits don't compile: `src/transports/http.c:89:2: error: unknown type name 'git_http_authtype_t'`. The last one seems pretty plausible.

cc @ethomson

### PR DESCRIPTION
**Pull request by pks-t**
In commit b9c5b15a7 (http: use the new httpclient, 2019-12-22), the HTTP
code got refactored to extract a generic HTTP client that operates
independently of the Git protocol. Part of refactoring was the creation
of a new `git_http_request` struct that encapsulates the generation of
requests. Our Git-specific HTTP transport was converted to use that in
`generate_request`, but during the process we forgot to set up custom
headers for the `git_http_request` and as a result we do not send out
these headers anymore.

Fix the issue by correctly setting up the request's custom headers.

---

Fixes #5385.

### CODE REVIEW

**Comment by ethomson** [comment]
Oops, what an embarassing oversight.  Thanks @pks-t, this looks good to me.

Maybe we should have a network test that adds an `Authorization` header so that we verify that we don't break this in the future.  (We can follow up with that later though to get this merged quickly.)

**Comment by pks-t** [comment]
> Maybe we should have a network test that adds an Authorization header so that we verify that we don't break this in the future. (We can follow up with that later though to get this merged quickly.)

I'd definitely love to have a fix. Let me see whether I can add one in online::clone using Basic auth.

**Comment by pks-t** [comment]
Amended a test. The test works for me if setting up my own creds and fails without the fix.

**Comment by pks-t** [comment]
Modified the test to not require any environment variables being set, as that caused CI to skip it.
