### ISSUE TITLE
devel/libgit2 1.3.0 fails to build, error: static declaration of 'HMAC_CTX_cleanup' follows non-static declaration

### ISSUE THREAD

**Issue by Nuadh** [libgit2/libgit2#6134]
libgit2-1.3.0 fails to build on FreeBSD 12.2-RELEASE-p11, due to me using libressl instead of openssl, with the following error:

/wrkdirs/usr/ports/devel/libgit2/work/libgit2-1.3.0/deps/ntlmclient/crypt_openssl.c:49:20: error: static declaration of 'HMAC_CTX_cleanup' follows non-static declaration
static inline void HMAC_CTX_cleanup(HMAC_CTX *ctx)
                   ^
/usr/local/include/openssl/hmac.h:90:6: note: previous declaration is here
void HMAC_CTX_cleanup(HMAC_CTX *ctx);

This issue was introduced with commit 5158b0b70ade89268b22b7c388802b5f5b6debce.

HMAC_CTX_cleanup was deprecated for public use and removed in a patch in 2015 (with version 1.1.0, I think) in openssl. For some reason, libressl still have this around. Attached is a (very minor) patch I used to "fix" this.

[patch-deps_ntlmclient_crypt__openssl.c.txt](https://github.com/libgit2/libgit2/files/7662305/patch-deps_ntlmclient_crypt__openssl.c.txt)
.

**Comment by Nuadh** [comment]
Actually working patch..

[patch-deps_ntlmclient_crypt__openssl.c.txt](https://github.com/libgit2/libgit2/files/7698092/patch-deps_ntlmclient_crypt__openssl.c.txt)

**Comment by belotn** [comment]
Hello,

Same here, `/usr/ports/devel/libgit2/work/libgit2-1.3.0/deps/ntlmclient/crypt_openssl.c:49:20: error: static declaration of 'HMAC_CTX_cleanup' follows non-static declaration
static inline void HMAC_CTX_cleanup(HMAC_CTX *ctx)`

**Comment by ethomson** [comment]
Thanks, this should be fixed by #6157.  Let me know if not!
