### ISSUE TITLE
0.99.0: kind of ABI/API changes issue

### ISSUE THREAD

**Issue by kloczek** [libgit2/libgit2#5415]
Looks like ABI/API changes in 0.99.0 are quitre subsptantial and by this libgit2-glib can ot be build 0.99.0. SONAME of the library changed as well (which is good in this case).

However pkgconfig file still is libgit2.pc. I think that probably it would be good to change it to libgit2-1.pc to not confuse pkgconfig detection.

**Comment by ethomson** [comment]
> Looks like ABI/API changes in 0.99.0 are quitre subsptantial and by this libgit2-glib can ot be build 0.99.0. SONAME of the library changed as well (which is good in this case).

Can you expand on this?  We expected no breaking API changes from v0.28.

**Comment by pks-t** [comment]
> Can you expand on this? We expected no breaking API changes from v0.28.

To expand a bit further on that: if there's any incompatibility except for the introduced return types (void -> int) in our public API, please open a bug report as we'd love to fix them.

**Comment by kloczek** [comment]
I see some incompatibilities issue on use 0.99.0
https://gitlab.gnome.org/GNOME/libgit2-glib/issues/6

If API is not compatible pkgconfig version should be bumped up. 
However in this case it may be some issue with 0.99.0 API :)

**Comment by pks-t** [comment]
Huh, interesting. Seems like libgit2-glib has been misusing the LIBGIT2_SOVERSION as a version check. In fact, they should've been checking against LIBGIT2_VER_{MAJOR,MINOR} instead. So the SOVERSION change was definitely a breaking change in that regard, but I'd much rather argue that the downstream code needs to be fixed instead.

I'm a bit on the fence with bumping pkgconfig versions. Our initial stance was that we only starting being backwards compatible with v1.0, and we've in fact tried hard to stay so since v0.28. In a post-1.0 world (which is going to start in a few weeks), we'll definitely bump the major version as well as the pkgconfig version when introducing breaking things. But for now I'd say to not bump the pkgconfig version.

Please feel free to disagree, though, I'm happy to be convinced otherwise. Especially with v1.0 I could see us moving to libgit2-1.0.pc.

**Comment by ethomson** [comment]
> `./libgit2-glib/ggit-patch.c:197:5: error: token ""0.99"" is not valid in preprocessor expressions`

This seems like a poor assumption in caller code that this would always be numeric.

> ../libgit2-glib/ggit-cred-plaintext.c:182:40: error: invalid use of incomplete typedef 'git_cred' {aka 'git_credential'}

This seems like a problem.

> Especially with v1.0 I could see us moving to libgit2-1.0.pc.

Sure, this seems reasonable.  Obviously it's too late to put the genie back in the 0.99 bottle though.

**Comment by ethomson** [comment]
> ../libgit2-glib/ggit-config.c:303:8: error: too few arguments to function 'git_config_add_file_ondisk'
>  303 |  ret = git_config_add_file_ondisk (_ggit_native_get (config),

This one is confusing, though.  Blame shows that this function's signature hasn't changed in years.

**Comment by ethomson** [comment]
> > ../libgit2-glib/ggit-cred-plaintext.c:182:40: error: invalid use of incomplete typedef 'git_cred' {aka 'git_credential'}

> This seems like a problem.

Aha.  There was a breaking change here in #5223.  I'm going to move those things into `include/git2/credential.h`

**Comment by ethomson** [comment]
> Aha. There was a breaking change here in #5223. I'm going to move those things into include/git2/credential.h

Meh.  I actually like that they're in `sys`.  @pks-t what do you think?

**Comment by pks-t** [comment]
On Sat, Mar 21, 2020 at 10:20:46AM -0700, Edward Thomson wrote:
> > Aha. There was a breaking change here in #5223. I'm going to move those things into include/git2/credential.h
> 
> Meh.  I actually like that they're in `sys`.  @pks-t what do you think?

I don't have any strong opinions on how to do it, but I think we should
unbreak application. Can we include "sys/credential.h" from
"credential.h" if built without hard deprecation? That'd leave them
where they are right now but still fix backwards compatibility.

**Comment by tiennou** [comment]
Sorry, that was part of an undercover attempt at limiting libssh2's API exposure from our public API. I think your suggested fix is okay @pks-t, though maybe there's something to revisit if the breakage is too much ?

**Comment by ethomson** [comment]
No problem, I like the thinking of moving it into `sys`.  I'll tease what we need to out of `sys/credential.h` and into `credential.h` today and open a PR.

**Comment by pks-t** [comment]
Thanks a lot for your report, @kloczek and for your input respetively fix @tiennou and @ethomson!
