### ISSUE TITLE
Build failure on Win32 with embedded libssh2 newer than 1.6.0

### ISSUE THREAD

**Issue by beniamino38** [libgit2/libgit2#4302]
### Reproduction steps
Using MS Visual Studio 2010 (32-bit), and 32-bit cmake 3.8.2 on a 64-bit Windows 10 machine
```
$ cmake -DBUILD_CLAR=OFF -DEMBED_SSH_PATH=../libssh2 -DCMAKE_INSTALL_PREFIX=./debug ..
$ cmake --build .
```

### Expected behavior
This works fine using libssh2 1.6.0, but fails with libssh2 1.7.0 or later. Libssh2 1.7.0 builds fine by itself, and only fails when embedded in libgit2.

### Actual behavior
```
"C:\Users\Ben\monitor\freeze\libgit2\build\git2.vcxproj" (default target) (3) ->
(ClCompile target) ->
  ..\..\libssh2\src\scp.c(729): error C2039: 'st_mtim' : is not a member of '_stat64' [C:\Users\Ben\monitor\freeze\libgit2\build\git2.vcxproj]
  ..\..\libssh2\src\scp.c(730): error C2039: 'st_atim' : is not a member of '_stat64' [C:\Users\Ben\monitor\freeze\libgit2\build\git2.vcxproj]
  ..\..\libssh2\src\scp.c(785): error C2039: 'st_mtim' : is not a member of '_stat64' [C:\Users\Ben\monitor\freeze\libgit2\build\git2.vcxproj]
  ..\..\libssh2\src\scp.c(786): error C2039: 'st_atim' : is not a member of '_stat64' [C:\Users\Ben\monitor\freeze\libgit2\build\git2.vcxproj]

    83 Warning(s)
    4 Error(s)
```

### Version of libgit2 (release number or SHA1)
0e165686d97264c2d7bc6b0317cf953581cbf695 but the same problem occurs for previous versions

### Operating system(s) tested
64-bit Windows 10

**Comment by beniamino38** [comment]
The problem began with libssh2 commit 6c84a426beb494980579e5c1d244ea54d3fc1a3f. A workaround is:
```
cd libssh2
sed -i".bak" "s/#ifdef LIBSSH2_USE_WIN32_LARGE_FILES/#ifdef XXX_DISABLED/" include/libssh2.h
sed -i".bak" "s/#ifdef LIBSSH2_USE_WIN32_SMALL_FILES/#ifdef XXX_DISABLED/" include/libssh2.h
```
