### ISSUE TITLE
libgit2 doesn't build on CentOS 6

### ISSUE THREAD

**Issue by richardwhiuk** [libgit2/libgit2#5246]
### Reproduction steps

On CentOS 6, the code in 08cfa43d0e1a9214a2f1239593686078e75e5636 fails to build - build output below. 

Specifically:

```
/usr/bin/cc -O3 -ffunction-sections -fdata-sections -fPIC -m64 -I /tmp/cargo-installcrsMpR/release/build/libgit2-sys-df5fb77be42fe6ea/out/include -I libgit2/src -I libgit2/deps/http-parser -I libgit2/deps/pcre -I /tmp/cargo-installcrsMpR/release/build/libssh2-sys-71669e04ccf20456/out/include -I /usr/local/gnu/include -fvisibility=hidden -DGIT_REGEX_BUILTIN=1 -DHAVE_STDINT_H=1 -DHAVE_MEMMOVE=1 -DNO_RECURSE=1 -DNEWLINE=10 -DPOSIX_MALLOC_THRESHOLD=10 -DLINK_SIZE=2 -DPARENS_NEST_LIMIT=250 -DMATCH_LIMIT=10000000 -DMATCH_LIMIT_RECURSION=MATCH_LIMIT -DMAX_NAME_SIZE=32 -DMAX_NAME_COUNT=10000 -DSHA1DC_NO_STANDARD_INCLUDES=1 '-DSHA1DC_CUSTOM_INCLUDE_SHA1_C="common.h"' '-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C="common.h"' -o /tmp/cargo-installcrsMpR/release/build/libgit2-sys-df5fb77be42fe6ea/out/build/libgit2/src/transports/ssh.o -c libgit2/src/transports/ssh.c
```

fails.

### Expected behavior

Builds correctly.

### Actual behavior

Fails to build with:

```
/tmp/cargo-installcrsMpR/release/build/libssh2-sys-71669e04ccf20456/out/include/libssh2.h:276: error: redefinition of typedef ‘LIBSSH2_USERAUTH_KBDINT_PROMPT’
/tmp/cargo-installcrsMpR/release/build/libgit2-sys-df5fb77be42fe6ea/out/include/git2/transport.h:168: note: previous declaration of ‘LIBSSH2_USERAUTH_KBDINT_PROMPT’ was here
/tmp/cargo-installcrsMpR/release/build/libssh2-sys-71669e04ccf20456/out/include/libssh2.h:282: error: redefinition of typedef ‘LIBSSH2_USERAUTH_KBDINT_RESPONSE’
/tmp/cargo-installcrsMpR/release/build/libgit2-sys-df5fb77be42fe6ea/out/include/git2/transport.h:169: note: previous declaration of ‘LIBSSH2_USERAUTH_KBDINT_RESPONSE’ was here
/tmp/cargo-installcrsMpR/release/build/libssh2-sys-71669e04ccf20456/out/include/libssh2.h:362: error: redefinition of typedef ‘LIBSSH2_SESSION’
/tmp/cargo-installcrsMpR/release/build/libgit2-sys-df5fb77be42fe6ea/out/include/git2/transport.h:167: note: previous declaration of ‘LIBSSH2_SESSION’ was here
```

### Version of libgit2 (release number or SHA1)

`08cfa43d0e1a9214a2f1239593686078e75e5636`

### Operating system(s) tested

Broken on CentOS 6
Works on CentOS 7 + Ubuntu 18.04

### Root cause analysis

This is caused by `include/git2/transport.h` being included before `libssh2.h`, due to the following include path:

```
src/transports/ssh.c
  src/transports/ssh.h
    include/git2/common.h
      include/git2/deprecated.h
        include/git2/clone.h
          include/git2/remote.h
           include/git2/transport.h
```

which occurs before `ssh.c` includes `libssh2.h`.

This means that `LIBSSH2_VERSION` isn't defined, which results in the double definition.

It's not obvious to me why this only affects CentOS 6 (it doesn't appear to affect CentOS 7 or Ubuntu 18.04).

This was previously fixed in https://github.com/libgit2/libgit2/pull/2461 , but has been regressed by https://github.com/libgit2/libgit2/pull/4979 which added `deprecated.h`.

The obvious fix, I think, is for `include/git2/transport.h` to include `libssh2.h` - but it's not obvious why we didn't do that before.

**Comment by pks-t** [comment]
Thanks for your bug report!

The problem we have is that we only want to include <libssh2.h> if libgit2 is actually compiled with libssh2 as transport. On other systems, we cannot include it as the header might not be available after all. We also cannot conditionally include it here, as we don't know whether we the backend is available while compiling libgit2 -- that information is part of "features.h", which gets generated from "features.h.in", and that is only for use in internal headers, not in external ones.

I'd call it a complete misfeature that we defined transport-specific types as part of our public API, but we unfortunately are stuck with that for now. So I guess the stop-gap solution for this would be to just move up the <libssh2.h> include in "ssh.c", even though it's not a nice solution.

If anybody else has a proposal, I'd definitely be open to hear it. Otherwise: would you like to create a pull request to fix this issue?

**Comment by richardwhiuk** [comment]
Note, this appears to be specific to GCC < 4.7 - with 4.7, this works.

**Comment by ethomson** [comment]
This is stale; we now test on CentOS in our nightlies.
