### ISSUE TITLE
Mac OS X 10.6 and earlier: Undefined symbols: _strnlen

### ISSUE THREAD

**Issue by ryandesign** [libgit2/libgit2#2009]
libgit2 0.20.0 builds fine on Mac OS X 10.7, 10.8, and 10.9, but fails on 10.6 (and presumably earlier) with this error:

```
Undefined symbols:
  "_strnlen", referenced from:
      _git_index_read in index.c.o
      _git_index_read in index.c.o
      _git_index_read in index.c.o
      _git_index_read in index.c.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
```

Full log: https://build.macports.org/builders/buildports-snowleopard-x86_64/builds/23352/steps/compile/logs/stdio
